# Generated by Django 2.2.2 on 2019-06-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('address', models.CharField(default='', max_length=80)),
                ('city', models.CharField(default='', max_length=60)),
                ('state', models.CharField(default='', max_length=40)),
                ('zip_code', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=40)),
                ('userprofile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pantry', to='pantry_app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Enter item or product name', max_length=40)),
                ('description', models.CharField(default='', max_length=40)),
                ('size', models.CharField(default='', max_length=20)),
                ('is_perishable', models.BooleanField(default=True)),
                ('expiration_date', models.DateField(help_text='For produce w/o exp date consider adding 6 days to purchase date')),
                ('purchase_date', models.DateField()),
                ('pantry', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pantry_app.Pantry')),
                ('userprofile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pantry_app.UserProfile')),
            ],
        ),
    ]
